name: Build Image and Deploy to Docker Hub

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_WEDDING_DAY=${{ vars.NEXT_PUBLIC_WEDDING_DAY }}" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t digital-wedding:latest .
          docker save digital-wedding:latest -o digital-wedding.tar
          chmod 644 digital-wedding.tar

      - name: Upload tar to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "digital-wedding.tar"
          target: "/var/app/"
          overwrite: true

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/app
            docker load -i digital-wedding.tar
            docker stop digital-wedding || true
            docker rm digital-wedding || true
            docker run -d --name digital-wedding --network digital-wedding-net -p 3005:3000 digital-wedding:latest